<template>
<div>
    <sidemenu active="/pubs"></sidemenu>
    <div class="page-content">
        <div class="header">
            <b-container>
                <a href="https://brainlife.io/docs/user/publication/" target="doc" style="margin: 10px; opacity: 0.4; float: right;"><icon name="book" scale="1.5"/></a>
                <h3>Publications</h3>
                <p style="opacity: 0.7; margin: 0px;">
                    Publicly accessible datasets generated by Brainlife Apps
                </p>
                <br>
            </b-container>
        </div>
        <b-container>
            <div v-if="!pubs" style="margin: 40px;"><h3>Loading ..</h3></div>
            <div v-else style="margin: 10px 0px;">
                <div v-for="pub in pubs" :key="pub._id" class="pub">
                    <pubcard :pub="pub"/>
                </div>
            </div>
        </b-container>
    </div>
</div>
</template>

<script>
import Vue from 'vue'
//import pageheader from '@/components/pageheader'
import sidemenu from '@/components/sidemenu'
import pubcard from '@/components/pubcard'

export default {
    components: { sidemenu, pubcard },
    data () {
        return {
            pubs: [],
            config: Vue.config,
        }
    },

    created: function() {
        this.$http.get('pub', {params: {
            find: JSON.stringify({ 
                removed: false 
            }),
            populate: 'project',
            deref_contacts: true,
        }})
        .then(res=>{
            this.pubs = res.data.pubs;
        }, res=>{
            console.error(res);
        });
    },

    methods: {
    }
}
</script>

<style scoped>
.pub {
margin-bottom: 10px;
}
.page-content {
top: 0px;
background-color: #eee;
}
.page-content h3 {
color: #999;
margin-bottom: 0px;
padding: 10px 0px;
}
.header {
padding: 10px;
background-color: white;
border-bottom: 1px solid #eee;
position: sticky;
z-index: 1;
top: 0px;
}
</style>
