<template>
<div class="groupanalysis">
    <div v-if="selected">
        <div class="selected-controller">
            <div class="button" @click="selected = null"><icon name="times"/> Close</div>
        </div>
        <iframe :src="host+'/ipython/'+selected.port+'/lab?token='+selected.token" frameBorder="0"/>
    </div>
    <div v-else-if="ready" class="home">
        <!--
        <div class="welcome" v-if="tasks.length == 0">
            <b-alert show variant="warning">Experimental</b-alert>
            <p>
                Welcome to the Group Analysis homepage. Here, you can launch various ipython notebooks
                that allows you to analyze archived output data generated by your processes. 
            </p>
        </div>
        -->
        <div class="list" style="background-color: white;">
            <!--
            <div class="ga-container header" v-if="tasks.length > 0">
                <b-row>
                    <b-col cols="4">
                        Description
                    </b-col>
                    <b-col cols="3">
                        Creator
                    </b-col>
                    <b-col cols="5">
                        Status
                    </b-col>
                </b-row>
            </div>
            <div v-for="task in tasks" :key="task._id">
                <div v-if="task.status != 'removed'" class="ga-container">
                    <b-row>
                        <b-col cols="4">
                            <small v-if="task.config"> {{task.config.container}} </small>
                            {{task.desc}}
                            <small>{{task._id}}</small>
                        </b-col>
                        <b-col cols="3">
                            <contact :id="task.user_id" size="small"/>
                            <time style="float: right"><timeago :datetime="task.create_date" :auto-update="60"/></time>
                        </b-col>
                        <b-col cols="5">
                            <b-button-group style="float: right">
                                <b-dropdown right split text="Open" variant="primary" @click="open(task)">
                                    <b-dropdown-item v-if="task.status == 'running' || task.status == 'requested'" title="Stop" @click="stop(task)">
                                        <icon name="stop-circle"/> Stop
                                    </b-dropdown-item>
                                    <b-dropdown-item v-if="task.status == 'stopped' || task.status == 'failed'" title="Rerun" @click="rerun(task)">
                                        <icon name="play"/> Rerun
                                    </b-dropdown-item>
                                    <b-dropdown-divider></b-dropdown-divider>
                                    <b-dropdown-item title="Remove this container" @click="remove(task)">
                                        <icon name="trash"/> Remove
                                    </b-dropdown-item>
                                </b-dropdown>
                            </b-button-group>

                            <statustag :status="task.status"/><br>
                            {{task.status_msg}}
                        </b-col>
                    </b-row>
                </div>
            </div>
            -->

            <h4>Existing Analysis</h4>
            <div>
                <div style="display: inline-block; width: 300px; margin-right: 10px; margin-bottom: 10px;" 
                    v-for="task in tasks.filter(task=>task.status != 'removed')" :key="task._id">
                    <div class="card ga-card">
                        <div class="card-body">
                            <h5 class="card-title"><icon name="flask"/> {{task.name}}</h5>
                            <p class="card-text" style="min-height: 60px;">{{task.desc}}<br> 
                                <small>{{task.config.container}}</small>
                            </p>
                            <b-button variant="primary" size="sm" @click="open(task)" :disabled="task._id == openWhenReady"><icon name="play"/> Open</b-button>
                            <div class="button" style="float: right;" variant="secondary" size="sm" @click="remove(task)"><icon name="trash"/></div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"><statustag :status="task.status"/></small><br>
                            <small style="font-size: 70%">{{task.status_msg}} {{task._id}}</small><br>
                        </div>
                    </div>
                </div>
            </div>

            <br>
        </div>

        <div class="list">
            
            <h4>New Analysis</h4>
            <div>
                <div style="display: inline-block; width: 200px; margin-right: 10px; margin-bottom: 10px;" v-for="(app, idx) in apps" :key="idx">
                    <div class="card ga-card">
                        <img class="card-img-top" :src="app.img">
                        <div class="card-body">
                            <p>
                                <b-button variant="success" size="sm" @click="launch(app)"><icon name="play"/> Launch</b-button>
                            </p>
                            <b-card-text style="min-height: 110px;">{{app.desc}}</b-card-text>
                        </div>
                        <!--
                        <div class="card-footer">
                            <small class="text-muted">{{app.container}}:{{app.tag}}</small>
                        </div>
                        -->
                    </div>
                </div>
            </div>
        </div>

        <!--
        <b-button @click="launch" class="button-fixed" v-b-tooltip.hover title="Launch New Analysis">
            <icon name="plus" scale="2"/>
        </b-button>
        -->
    </div>
    <div v-else class="home">
        <p style="padding: 20px">Loading...</p>
    </div>
</div>
</template>

<script>
import Vue from 'vue'

import agreementMixin from '@/mixins/agreement'
import ReconnectingWebSocket from 'reconnectingwebsocket'

export default {
    mixins: [agreementMixin],
    components: {
        'contact': ()=> import('@/components/contact'),
        'statustag': ()=> import('@/components/statustag'),
    },

    props: {
        project: { type: Object },
    },

    data() {
        return {
            //currently opened group analysis container
            tasks: [],
            selected: null,
            host: "",

            openWhenReady: null,

            instance: null,

            ws: null, //websocket

            //will come from db someday
            apps: [
                {
                    name: "Brainlife dipy Jupyter Notebook", 
                    img: "https://kanoki.org/wp-content/uploads/2017/07/Screen-Shot-2017-07-15-at-04.59.36.png",
                    desc: "Jupyter Datascience Notebook (lab-2.1.1) with Dipy and Fury",
                    container: "brainlife/ga-dipy",
                    tag: "1.0",
                },
                {
                    name: "Brainlife Octave(matlab) Jupyter Notebook", 
                    img: "https://kanoki.org/wp-content/uploads/2017/07/Screen-Shot-2017-07-15-at-04.59.36.png",
                    desc: "Jupyter Datascience Notebook (lab-2.1.1) with Octave",
                    container: "brainlife/ga-octave",
                    tag: "1.0",
                },
                {
                    name: "Jupyter Datascience Lab", 
                    img: "https://kanoki.org/wp-content/uploads/2017/07/Screen-Shot-2017-07-15-at-04.59.36.png",
                    desc: "Jupyter Datascience Notebook (lab-2.1.1)",
                    container: "jupyter/datascience-notebook", 
                    tag: "lab-2.1.1", 
                },
                {
                    name: "Jupyter Scipy Notebook", 
                    img: "https://kanoki.org/wp-content/uploads/2017/07/Screen-Shot-2017-07-15-at-04.59.36.png",
                    //img: "https://www.dataquest.io/wp-content/uploads/2019/01/interface-screenshot.png",
                    desc: "Jupyter Notebook Scientific Python Stack from https://github.com/jupyter/docker-stacks",
                    container: "jupyter/scipy-notebook", 
                    tag: "latest",
                },   
                {
                    name: "Jupyter Tensorflow Notebook", 
                    //img: "https://i.imgur.com/n0PmXQn.gif",
                    img: "https://kanoki.org/wp-content/uploads/2017/07/Screen-Shot-2017-07-15-at-04.59.36.png",
                    desc: "Jupyter Notebook Scientific Python Stack w/ Tensorflow from https://github.com/jupyter/docker-stacks",
                    container: "jupyter/tensorflow-notebook", 
                    tag: "latest",
                },
            ],

            ready: false,
            config: Vue.config,
        }
    },

    destroyed() {
        if(this.ws) {
            console.log("disconnecting from ws - process");
            this.ws.close();
        }
    },

    mounted() {
        if(Vue.config.debug) {
            this.host = "https://dev1.soichi.us";
        }

        this.find_or_create_instance((err, instance)=>{
            if(err) return console.error(err); //TODO notify?
            this.instance = instance;

            //subscribe to task update
            var url = Vue.config.event_ws+"/subscribe?jwt="+Vue.config.jwt;
            this.ws = new ReconnectingWebSocket(url, null);
            this.ws.onopen = (e)=>{
                console.log("subscribing to group analysis instance");
                //wf.task will be deprecated by ex:amaretti
                this.ws.send(JSON.stringify({
                    bind: {
                        ex: "wf.task",
                        key: this.instance._id+".#",
                    }
                }));
                this.ws.onmessage = (json)=>{
                    let event = JSON.parse(json.data);
                    switch(event.dinfo.exchange) {
                    case "wf.task":
                        let task = event.msg;
                        //console.dir(task);
                        let existing_task = this.tasks.find(t=>t._id == task._id);
                        if(existing_task) {
                            for(let k in task) existing_task[k] = task[k];
                        } else this.tasks.push(task); //new task

                        if(this.openWhenReady == task._id && task.status == "running" && task.status_msg == "running") {
                            this.openWhenReady = null;
                            this.jump(task); 
                        }
                    }
                }
            }

            //load initial list of tasks
            this.$http.get(Vue.config.amaretti_api+'/task', {
                params: {
                    find: JSON.stringify({
                        status: {$ne: "removed"},
                        instance_id: this.instance._id,
                    }),
                }
            }).then(res=>{
                this.tasks = res.data.tasks;
                this.ready = true;
            });
        });
    },

    methods: {
        find_or_create_instance(cb) {
            //find or create an instance to host all ga tasks
            let key = {
                group_id: this.project.group_id,
                name: "ga-launchers",
            }
            this.$http.get(Vue.config.amaretti_api+'/instance', {
                params: {
                    find: JSON.stringify(key),
                },
            }).then(res=>{
                if(res.data.instances.length == 1) return cb(null, res.data.instances[0]);
                //create new instance
                this.$http.post(Vue.config.amaretti_api+'/instance', key).then(res=>{
                    cb(null, res.data);
                }).catch(cb);
            }).catch(cb);
        },

        /*
        launch() {
            this.check_agreements(this.project, err=>{
                if(err) return this.cb(err);
                this.$root.$emit("galauncher.open", {
                    instance: this.instance,
                    cb: (err, task)=>{
                        if(err) return console.error(err);
                        console.log("submitted launcher");
                        console.dir(task);
                    }
                });
            });
        },
        */

        launch(app) {
            this.check_agreements(this.project, err=>{
                if(err) return this.cb(err);
                this.$http.post('secondary/launchga', {
                    instance_id: this.instance._id,

                    container: app.container,
                    tag: app.tag,

                    name: app.name, 
                    desc: app.desc, //TODO..
                    //config: {},
                }).then(res=>{
                    let task = res.data;
                    this.$notify("Creating Analysis..");
                    this.openWhenReady = task._id;
                }).catch(console.error);
            });
        },

        remove(task) {
            this.$http.delete(Vue.config.amaretti_api+"/task/"+task._id).then(res=>{
                if(res.status == 200) {
                    this.$notify("Removal request submitted");
                }
            });
        },

        /*
        stop(task) {
            this.$http.put(Vue.config.amaretti_api+"/task/stop/"+task._id).then(res=>{
                if(res.status == 200) {
                    this.$notify("Stop request submitted");
                }
            });
        },

        rerun(task) {
            this.$http.put(Vue.config.amaretti_api+"/task/rerun/"+task._id).then(res=>{
                if(res.status == 200) {
                    this.$notify("Rerun request submitted");
                }
            });
        },
        */

        open(task) {
            switch(task.status) {
            case "requested":
                this.openWhenReady = task._id;
                break;
            case "stop_requested":
            case "stopped":
                //rerun
                this.$http.put(Vue.config.amaretti_api+"/task/rerun/"+task._id).then(res=>{
                    if(res.status == 200) {
                        this.$notify("Rerun request submitted");
                        this.openWhenReady = task._id;
                    }
                });
                break;
            case "running":
                this.jump(task);
                break;
            default:
                console.error("unknown task state");
                console.dir(task.status); 
            } 
        },

        jump(task) {
            /*
            if(task.status_msg != 'running') {
                alert('please wait until the container starts running');
                return;
            }
            */

            this.$http.get(Vue.config.amaretti_api+"/task/download/"+task._id+'/container.json').then(res=>{
                if(res.status == 200) {
                    this.selected = res.data; 
                } else {
                    //TODO - poll for container.json automatically..
                    this.$notify("Please wait for the container to fully start");
                }
            });
        },
    }
}
</script>

<style scoped>
.home {
    position: fixed;
    left: 40px;
    right: 0;
    top: 95px;
    bottom: 0;
    overflow: auto;
}
.list .h4 {
opacity: 0.8;
text-transform: uppercase;
}
.home .welcome {
    margin: 20px;
}
.list {
    padding: 20px;
}
.new {
    padding: 20px;
    background-color: white;
}
iframe {
    position: fixed;
    left: 40px;
    top: 95x;
    width: calc(100% - 40px);
    height: calc(100% - 95px)
}
.selected-controller {
    position: fixed;
    text-align: right;
    padding-right: 10px;
    width: 100px;
    right: 0;
    height: 25px;
    top: 95px;
    z-index: 1;
}
.ga-container {
    padding: 5px;
    background-color: white;
    margin-bottom: 1px;
}
.ga-container.header {
    background-color: inherit;
    opacity: 0.5;
    text-transform: uppercase;
    font-weight: bold;
}
.ga-card {
border-radius: 5px;
margin-bottom: 10px;
box-shadow: 2px 2px 4px #0001;
}
.ga-card .card-body {
padding: 10px;
}
</style>

